from decimal import Decimal


HIGH_AMOUNT_THRESHOLD = Decimal("10000")
VERY_HIGH_AMOUNT_THRESHOLD = Decimal("50000")

NEW_DEVICE_SCORE = 20
HIGH_AMOUNT_SCORE = 25
VERY_HIGH_AMOUNT_SCORE = 40
HIGH_VELOCITY_SCORE = 30

VELOCITY_TRANSACTION_LIMIT = 3
VELOCITY_WINDOW_SECONDS = 60